name: Test.
on:
  push:
    branches: [ main ]

jobs:
  build:
    if: github.repository_owner == 'AuroraEditor'
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v3
      - name: Create config.php
        env:
          WEBHOOK: ${{ secrets.DISCORD_TEST_HOOK }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "<?php
          \$settings = array(
              \"username\" => \"aurora-editor-bot\",
              \"admins\" => array(\"0xWDG\"),
              \"github_token" => \"$TOKEN\",
              \"discord_webhook" => \"$WEBHOOK\",
              \"serverURL\" => \"https://apps.wesleydegroot.nl/AuroraEditorBot/\"
          );" > config.php

      - name: Run test (accept_pr.json)
        run: php index.php accept_pr.json

      - name: Run test (issue.json)
        run: php index.php issue.json

      - name: Run test (please_assign_me.json)
        run: php index.php please_assign_me.json

      - name: Run test (pr.json)
        run: php index.php pr.json
