name: Test payloads
on:
  push:
    branches: [ main ]

jobs:
  test:
    if: github.repository_owner == 'AuroraEditor'
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v3
      - name: Create config.php
        run: |
          echo "<?php 
          \$settings = array(
              \"username\" => \"aurora-editor-bot\",
              \"admins\" => array(\"0xWDG\",\"aurora-editor-bot\"),
              \"github_token\" => \"${{ secrets.BOT_TOKEN }}\",
              \"discord_webhook\" => \"${{ secrets.DISCORD_TEST_HOOK }}\",
              \"serverURL\" => \"https://auroraeditor.github.io/AuroraEditor/AuroraEditorBot/\"
          );" > config.php

      - name: Run test (issue.json)
        run: |
          php index.php issue.json
          sleep 2

      - name: Run test (please_assign_me.json)
        run: |
          php index.php please_assign_me.json
          sleep 2
          
      - name: Run test (pr.json)
        run: |
          php index.php pr.json
          sleep 2

      - name: Run test (reject_pr.json)
        run: |
          php index.php reject_pr.json
          sleep 2

      - name: Run test (accept_pr.json)
        run: |
          php index.php accept_pr.json
          sleep 2

      - name: Remove config.php
        run: rm config.php
